<?php
/**
 * SearchByMetricTireApi
 * PHP version 5
 *
 * @category Class
 * @package  WheelSizeApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wheel Fitment API
 *
 * The Wheel Fitment API provides a programmatic gateway to the comprehensive database and services of www.wheel-size.com. This API is expertly designed to retrieve detailed information regarding the vehicle fitment database for rims and tires, encompassing both original equipment (OE) and  aftermarket fitments, along with plus/minus sizing fitment data. Our offerings are further diversified  by including a multitude of country-specific and language-specific options.  We take pride in the extensive coverage of our fitment data, which nearly spans 100% for vehicles manufactured since the year 2000. Moreover, to ensure the utmost accuracy and relevance of the information we provide, our fitment data is meticulously updated on a daily basis.
 *
 * OpenAPI spec version: v2
 * Contact: info@wheel-size.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace WheelSizeApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use WheelSizeApiClient\ApiException;
use WheelSizeApiClient\Configuration;
use WheelSizeApiClient\HeaderSelector;
use WheelSizeApiClient\ObjectSerializer;

/**
 * SearchByMetricTireApi Class Doc Comment
 *
 * @category Class
 * @package  WheelSizeApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchByMetricTireApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation aspectRatio
     *
     * List aspect ratios
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (optional)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \WheelSizeApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WheelSizeApiClient\Model\AspectRatioMetricReportOutput
     */
    public function aspectRatio($section_width = null, $region = null, $ordering = null)
    {
        list($response) = $this->aspectRatioWithHttpInfo($section_width, $region, $ordering);
        return $response;
    }

    /**
     * Operation aspectRatioWithHttpInfo
     *
     * List aspect ratios
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (optional)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \WheelSizeApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WheelSizeApiClient\Model\AspectRatioMetricReportOutput, HTTP status code, HTTP response headers (array of strings)
     */
    public function aspectRatioWithHttpInfo($section_width = null, $region = null, $ordering = null)
    {
        $returnType = '\WheelSizeApiClient\Model\AspectRatioMetricReportOutput';
        $request = $this->aspectRatioRequest($section_width, $region, $ordering);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WheelSizeApiClient\Model\AspectRatioMetricReportOutput',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation aspectRatioAsync
     *
     * List aspect ratios
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (optional)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aspectRatioAsync($section_width = null, $region = null, $ordering = null)
    {
        return $this->aspectRatioAsyncWithHttpInfo($section_width, $region, $ordering)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aspectRatioAsyncWithHttpInfo
     *
     * List aspect ratios
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (optional)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aspectRatioAsyncWithHttpInfo($section_width = null, $region = null, $ordering = null)
    {
        $returnType = '\WheelSizeApiClient\Model\AspectRatioMetricReportOutput';
        $request = $this->aspectRatioRequest($section_width, $region, $ordering);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aspectRatio'
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (optional)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function aspectRatioRequest($section_width = null, $region = null, $ordering = null)
    {
        if ($ordering !== null && strlen($ordering) < 1) {
            throw new \InvalidArgumentException('invalid length for "$ordering" when calling SearchByMetricTireApi.aspectRatio, must be bigger than or equal to 1.');
        }


        $resourcePath = '/by_tire/ar/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($section_width !== null) {
            $queryParams['section_width'] = ObjectSerializer::toQueryValue($section_width);
        }
        // query params
        if (is_array($region)) {
            $queryParams['region'] = $region;
        } else
        if ($region !== null) {
            $queryParams['region'] = ObjectSerializer::toQueryValue($region);
        }
        // query params
        if ($ordering !== null) {
            $queryParams['ordering'] = ObjectSerializer::toQueryValue($ordering);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation diameters
     *
     * List rim diameters
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (optional)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (optional)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \WheelSizeApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WheelSizeApiClient\Model\RimDiameterMetricReportOutput
     */
    public function diameters($section_width = null, $aspect_ratio = null, $region = null, $ordering = null)
    {
        list($response) = $this->diametersWithHttpInfo($section_width, $aspect_ratio, $region, $ordering);
        return $response;
    }

    /**
     * Operation diametersWithHttpInfo
     *
     * List rim diameters
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (optional)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (optional)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \WheelSizeApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WheelSizeApiClient\Model\RimDiameterMetricReportOutput, HTTP status code, HTTP response headers (array of strings)
     */
    public function diametersWithHttpInfo($section_width = null, $aspect_ratio = null, $region = null, $ordering = null)
    {
        $returnType = '\WheelSizeApiClient\Model\RimDiameterMetricReportOutput';
        $request = $this->diametersRequest($section_width, $aspect_ratio, $region, $ordering);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WheelSizeApiClient\Model\RimDiameterMetricReportOutput',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation diametersAsync
     *
     * List rim diameters
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (optional)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (optional)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function diametersAsync($section_width = null, $aspect_ratio = null, $region = null, $ordering = null)
    {
        return $this->diametersAsyncWithHttpInfo($section_width, $aspect_ratio, $region, $ordering)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation diametersAsyncWithHttpInfo
     *
     * List rim diameters
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (optional)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (optional)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function diametersAsyncWithHttpInfo($section_width = null, $aspect_ratio = null, $region = null, $ordering = null)
    {
        $returnType = '\WheelSizeApiClient\Model\RimDiameterMetricReportOutput';
        $request = $this->diametersRequest($section_width, $aspect_ratio, $region, $ordering);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'diameters'
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (optional)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (optional)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function diametersRequest($section_width = null, $aspect_ratio = null, $region = null, $ordering = null)
    {
        if ($ordering !== null && strlen($ordering) < 1) {
            throw new \InvalidArgumentException('invalid length for "$ordering" when calling SearchByMetricTireApi.diameters, must be bigger than or equal to 1.');
        }


        $resourcePath = '/by_tire/rd/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($section_width !== null) {
            $queryParams['section_width'] = ObjectSerializer::toQueryValue($section_width);
        }
        // query params
        if ($aspect_ratio !== null) {
            $queryParams['aspect_ratio'] = ObjectSerializer::toQueryValue($aspect_ratio);
        }
        // query params
        if (is_array($region)) {
            $queryParams['region'] = $region;
        } else
        if ($region !== null) {
            $queryParams['region'] = ObjectSerializer::toQueryValue($region);
        }
        // query params
        if ($ordering !== null) {
            $queryParams['ordering'] = ObjectSerializer::toQueryValue($ordering);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchByTire
     *
     * Search by Metric Tire
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (required)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim **&#x60;diameter&#x60;** is the distance measured in inches across the face of the wheel, from bead seat to bead seat. You can use _**&#x60;GET /by_tire/rd&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;19&#x60;) (required)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $mode The **&#x60;Mode&#x60;** is used to set the search mode for data on the axes of wheelpairs. By default, the search uses the axles of the front and rear wheelset. **&#x60;Mode&#x60;** possible values: __*&#x60;both&#x60;*__, __*&#x60;front_only&#x60;*__ or __*&#x60;rear_only&#x60;*__. (e.g. &#x60;both&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;make&#x60;*, *&#x60;model&#x60;* (optional)
     *
     * @throws \WheelSizeApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WheelSizeApiClient\Model\SearchByMetricTireCarReportOutput
     */
    public function searchByTire($section_width, $aspect_ratio, $rim_diameter, $region = null, $mode = null, $ordering = null)
    {
        list($response) = $this->searchByTireWithHttpInfo($section_width, $aspect_ratio, $rim_diameter, $region, $mode, $ordering);
        return $response;
    }

    /**
     * Operation searchByTireWithHttpInfo
     *
     * Search by Metric Tire
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (required)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim **&#x60;diameter&#x60;** is the distance measured in inches across the face of the wheel, from bead seat to bead seat. You can use _**&#x60;GET /by_tire/rd&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;19&#x60;) (required)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $mode The **&#x60;Mode&#x60;** is used to set the search mode for data on the axes of wheelpairs. By default, the search uses the axles of the front and rear wheelset. **&#x60;Mode&#x60;** possible values: __*&#x60;both&#x60;*__, __*&#x60;front_only&#x60;*__ or __*&#x60;rear_only&#x60;*__. (e.g. &#x60;both&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;make&#x60;*, *&#x60;model&#x60;* (optional)
     *
     * @throws \WheelSizeApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WheelSizeApiClient\Model\SearchByMetricTireCarReportOutput, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchByTireWithHttpInfo($section_width, $aspect_ratio, $rim_diameter, $region = null, $mode = null, $ordering = null)
    {
        $returnType = '\WheelSizeApiClient\Model\SearchByMetricTireCarReportOutput';
        $request = $this->searchByTireRequest($section_width, $aspect_ratio, $rim_diameter, $region, $mode, $ordering);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WheelSizeApiClient\Model\SearchByMetricTireCarReportOutput',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchByTireAsync
     *
     * Search by Metric Tire
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (required)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim **&#x60;diameter&#x60;** is the distance measured in inches across the face of the wheel, from bead seat to bead seat. You can use _**&#x60;GET /by_tire/rd&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;19&#x60;) (required)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $mode The **&#x60;Mode&#x60;** is used to set the search mode for data on the axes of wheelpairs. By default, the search uses the axles of the front and rear wheelset. **&#x60;Mode&#x60;** possible values: __*&#x60;both&#x60;*__, __*&#x60;front_only&#x60;*__ or __*&#x60;rear_only&#x60;*__. (e.g. &#x60;both&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;make&#x60;*, *&#x60;model&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByTireAsync($section_width, $aspect_ratio, $rim_diameter, $region = null, $mode = null, $ordering = null)
    {
        return $this->searchByTireAsyncWithHttpInfo($section_width, $aspect_ratio, $rim_diameter, $region, $mode, $ordering)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchByTireAsyncWithHttpInfo
     *
     * Search by Metric Tire
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (required)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim **&#x60;diameter&#x60;** is the distance measured in inches across the face of the wheel, from bead seat to bead seat. You can use _**&#x60;GET /by_tire/rd&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;19&#x60;) (required)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $mode The **&#x60;Mode&#x60;** is used to set the search mode for data on the axes of wheelpairs. By default, the search uses the axles of the front and rear wheelset. **&#x60;Mode&#x60;** possible values: __*&#x60;both&#x60;*__, __*&#x60;front_only&#x60;*__ or __*&#x60;rear_only&#x60;*__. (e.g. &#x60;both&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;make&#x60;*, *&#x60;model&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByTireAsyncWithHttpInfo($section_width, $aspect_ratio, $rim_diameter, $region = null, $mode = null, $ordering = null)
    {
        $returnType = '\WheelSizeApiClient\Model\SearchByMetricTireCarReportOutput';
        $request = $this->searchByTireRequest($section_width, $aspect_ratio, $rim_diameter, $region, $mode, $ordering);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchByTire'
     *
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (required)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim **&#x60;diameter&#x60;** is the distance measured in inches across the face of the wheel, from bead seat to bead seat. You can use _**&#x60;GET /by_tire/rd&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;19&#x60;) (required)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $mode The **&#x60;Mode&#x60;** is used to set the search mode for data on the axes of wheelpairs. By default, the search uses the axles of the front and rear wheelset. **&#x60;Mode&#x60;** possible values: __*&#x60;both&#x60;*__, __*&#x60;front_only&#x60;*__ or __*&#x60;rear_only&#x60;*__. (e.g. &#x60;both&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;make&#x60;*, *&#x60;model&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function searchByTireRequest($section_width, $aspect_ratio, $rim_diameter, $region = null, $mode = null, $ordering = null)
    {
        // verify the required parameter 'section_width' is set
        if ($section_width === null || (is_array($section_width) && count($section_width) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $section_width when calling searchByTire'
            );
        }
        // verify the required parameter 'aspect_ratio' is set
        if ($aspect_ratio === null || (is_array($aspect_ratio) && count($aspect_ratio) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $aspect_ratio when calling searchByTire'
            );
        }
        // verify the required parameter 'rim_diameter' is set
        if ($rim_diameter === null || (is_array($rim_diameter) && count($rim_diameter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rim_diameter when calling searchByTire'
            );
        }
        if ($ordering !== null && strlen($ordering) < 1) {
            throw new \InvalidArgumentException('invalid length for "$ordering" when calling SearchByMetricTireApi.searchByTire, must be bigger than or equal to 1.');
        }


        $resourcePath = '/by_tire/search/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($section_width !== null) {
            $queryParams['section_width'] = ObjectSerializer::toQueryValue($section_width);
        }
        // query params
        if ($aspect_ratio !== null) {
            $queryParams['aspect_ratio'] = ObjectSerializer::toQueryValue($aspect_ratio);
        }
        // query params
        if ($rim_diameter !== null) {
            $queryParams['rim_diameter'] = ObjectSerializer::toQueryValue($rim_diameter);
        }
        // query params
        if (is_array($region)) {
            $queryParams['region'] = $region;
        } else
        if ($region !== null) {
            $queryParams['region'] = ObjectSerializer::toQueryValue($region);
        }
        // query params
        if ($mode !== null) {
            $queryParams['mode'] = ObjectSerializer::toQueryValue($mode);
        }
        // query params
        if ($ordering !== null) {
            $queryParams['ordering'] = ObjectSerializer::toQueryValue($ordering);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchByTireModifications
     *
     * Search by Metric Tire
     *
     * @param  string $make A car&#39;s **&#x60;Make&#x60;** is the brand of the vehicle. You can use _**&#x60;GET /makes/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;mitsubishi&#x60;) (required)
     * @param  string $model The particular **&#x60;Model&#x60;** of the brand. You can use _**&#x60;GET /models/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;outlander&#x60;) (required)
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (required)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim **&#x60;diameter&#x60;** is the distance measured in inches across the face of the wheel, from bead seat to bead seat. You can use _**&#x60;GET /by_tire/rd/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;19&#x60;) (required)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $mode The **&#x60;Mode&#x60;** is used to set the search mode for data on the axes of wheelpairs. By default, the search uses the axles of the front and rear wheelset. **&#x60;Mode&#x60;** possible values: __*&#x60;both&#x60;*__, __*&#x60;front_only&#x60;*__ or __*&#x60;rear_only&#x60;*__. (e.g. &#x60;both&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;make&#x60;*, *&#x60;model&#x60;*, *&#x60;trim&#x60;*, *&#x60;start_year&#x60;*, *&#x60;end_year&#x60;* (optional)
     * @param  int $limit limit (optional, default to 50)
     * @param  int $offset offset (optional, default to 0)
     *
     * @throws \WheelSizeApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WheelSizeApiClient\Model\SearchByMetricTireModificationReportOutput
     */
    public function searchByTireModifications($make, $model, $section_width, $aspect_ratio, $rim_diameter, $region = null, $mode = null, $ordering = null, $limit = '50', $offset = '0')
    {
        list($response) = $this->searchByTireModificationsWithHttpInfo($make, $model, $section_width, $aspect_ratio, $rim_diameter, $region, $mode, $ordering, $limit, $offset);
        return $response;
    }

    /**
     * Operation searchByTireModificationsWithHttpInfo
     *
     * Search by Metric Tire
     *
     * @param  string $make A car&#39;s **&#x60;Make&#x60;** is the brand of the vehicle. You can use _**&#x60;GET /makes/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;mitsubishi&#x60;) (required)
     * @param  string $model The particular **&#x60;Model&#x60;** of the brand. You can use _**&#x60;GET /models/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;outlander&#x60;) (required)
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (required)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim **&#x60;diameter&#x60;** is the distance measured in inches across the face of the wheel, from bead seat to bead seat. You can use _**&#x60;GET /by_tire/rd/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;19&#x60;) (required)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $mode The **&#x60;Mode&#x60;** is used to set the search mode for data on the axes of wheelpairs. By default, the search uses the axles of the front and rear wheelset. **&#x60;Mode&#x60;** possible values: __*&#x60;both&#x60;*__, __*&#x60;front_only&#x60;*__ or __*&#x60;rear_only&#x60;*__. (e.g. &#x60;both&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;make&#x60;*, *&#x60;model&#x60;*, *&#x60;trim&#x60;*, *&#x60;start_year&#x60;*, *&#x60;end_year&#x60;* (optional)
     * @param  int $limit (optional, default to 50)
     * @param  int $offset (optional, default to 0)
     *
     * @throws \WheelSizeApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WheelSizeApiClient\Model\SearchByMetricTireModificationReportOutput, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchByTireModificationsWithHttpInfo($make, $model, $section_width, $aspect_ratio, $rim_diameter, $region = null, $mode = null, $ordering = null, $limit = '50', $offset = '0')
    {
        $returnType = '\WheelSizeApiClient\Model\SearchByMetricTireModificationReportOutput';
        $request = $this->searchByTireModificationsRequest($make, $model, $section_width, $aspect_ratio, $rim_diameter, $region, $mode, $ordering, $limit, $offset);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WheelSizeApiClient\Model\SearchByMetricTireModificationReportOutput',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchByTireModificationsAsync
     *
     * Search by Metric Tire
     *
     * @param  string $make A car&#39;s **&#x60;Make&#x60;** is the brand of the vehicle. You can use _**&#x60;GET /makes/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;mitsubishi&#x60;) (required)
     * @param  string $model The particular **&#x60;Model&#x60;** of the brand. You can use _**&#x60;GET /models/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;outlander&#x60;) (required)
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (required)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim **&#x60;diameter&#x60;** is the distance measured in inches across the face of the wheel, from bead seat to bead seat. You can use _**&#x60;GET /by_tire/rd/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;19&#x60;) (required)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $mode The **&#x60;Mode&#x60;** is used to set the search mode for data on the axes of wheelpairs. By default, the search uses the axles of the front and rear wheelset. **&#x60;Mode&#x60;** possible values: __*&#x60;both&#x60;*__, __*&#x60;front_only&#x60;*__ or __*&#x60;rear_only&#x60;*__. (e.g. &#x60;both&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;make&#x60;*, *&#x60;model&#x60;*, *&#x60;trim&#x60;*, *&#x60;start_year&#x60;*, *&#x60;end_year&#x60;* (optional)
     * @param  int $limit (optional, default to 50)
     * @param  int $offset (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByTireModificationsAsync($make, $model, $section_width, $aspect_ratio, $rim_diameter, $region = null, $mode = null, $ordering = null, $limit = '50', $offset = '0')
    {
        return $this->searchByTireModificationsAsyncWithHttpInfo($make, $model, $section_width, $aspect_ratio, $rim_diameter, $region, $mode, $ordering, $limit, $offset)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchByTireModificationsAsyncWithHttpInfo
     *
     * Search by Metric Tire
     *
     * @param  string $make A car&#39;s **&#x60;Make&#x60;** is the brand of the vehicle. You can use _**&#x60;GET /makes/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;mitsubishi&#x60;) (required)
     * @param  string $model The particular **&#x60;Model&#x60;** of the brand. You can use _**&#x60;GET /models/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;outlander&#x60;) (required)
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (required)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim **&#x60;diameter&#x60;** is the distance measured in inches across the face of the wheel, from bead seat to bead seat. You can use _**&#x60;GET /by_tire/rd/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;19&#x60;) (required)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $mode The **&#x60;Mode&#x60;** is used to set the search mode for data on the axes of wheelpairs. By default, the search uses the axles of the front and rear wheelset. **&#x60;Mode&#x60;** possible values: __*&#x60;both&#x60;*__, __*&#x60;front_only&#x60;*__ or __*&#x60;rear_only&#x60;*__. (e.g. &#x60;both&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;make&#x60;*, *&#x60;model&#x60;*, *&#x60;trim&#x60;*, *&#x60;start_year&#x60;*, *&#x60;end_year&#x60;* (optional)
     * @param  int $limit (optional, default to 50)
     * @param  int $offset (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchByTireModificationsAsyncWithHttpInfo($make, $model, $section_width, $aspect_ratio, $rim_diameter, $region = null, $mode = null, $ordering = null, $limit = '50', $offset = '0')
    {
        $returnType = '\WheelSizeApiClient\Model\SearchByMetricTireModificationReportOutput';
        $request = $this->searchByTireModificationsRequest($make, $model, $section_width, $aspect_ratio, $rim_diameter, $region, $mode, $ordering, $limit, $offset);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchByTireModifications'
     *
     * @param  string $make A car&#39;s **&#x60;Make&#x60;** is the brand of the vehicle. You can use _**&#x60;GET /makes/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;mitsubishi&#x60;) (required)
     * @param  string $model The particular **&#x60;Model&#x60;** of the brand. You can use _**&#x60;GET /models/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;outlander&#x60;) (required)
     * @param  float $section_width **&#x60;Section width&#x60;** is the width of the tire in mm. You can use _**&#x60;GET /by_tire/sw/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;225&#x60;) (required)
     * @param  int $aspect_ratio The **&#x60;Aspect ratio&#x60;** is indicated on the tire sidewall as a percentage. It&#39;s the height of the sidewall measured from wheel rim to top of the tread, expressed as a percentage of tire width. You can use _**&#x60;GET /by_tire/ar/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;50&#x60;) (required)
     * @param  float $rim_diameter Rim **&#x60;diameter&#x60;** is the distance measured in inches across the face of the wheel, from bead seat to bead seat. You can use _**&#x60;GET /by_tire/rd/&#x60;**_ to get a list of available *&#x60;value&#x60;* values. (e.g. &#x60;19&#x60;) (required)
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $mode The **&#x60;Mode&#x60;** is used to set the search mode for data on the axes of wheelpairs. By default, the search uses the axles of the front and rear wheelset. **&#x60;Mode&#x60;** possible values: __*&#x60;both&#x60;*__, __*&#x60;front_only&#x60;*__ or __*&#x60;rear_only&#x60;*__. (e.g. &#x60;both&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;make&#x60;*, *&#x60;model&#x60;*, *&#x60;trim&#x60;*, *&#x60;start_year&#x60;*, *&#x60;end_year&#x60;* (optional)
     * @param  int $limit (optional, default to 50)
     * @param  int $offset (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function searchByTireModificationsRequest($make, $model, $section_width, $aspect_ratio, $rim_diameter, $region = null, $mode = null, $ordering = null, $limit = '50', $offset = '0')
    {
        // verify the required parameter 'make' is set
        if ($make === null || (is_array($make) && count($make) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $make when calling searchByTireModifications'
            );
        }
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling searchByTireModifications'
            );
        }
        // verify the required parameter 'section_width' is set
        if ($section_width === null || (is_array($section_width) && count($section_width) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $section_width when calling searchByTireModifications'
            );
        }
        // verify the required parameter 'aspect_ratio' is set
        if ($aspect_ratio === null || (is_array($aspect_ratio) && count($aspect_ratio) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $aspect_ratio when calling searchByTireModifications'
            );
        }
        // verify the required parameter 'rim_diameter' is set
        if ($rim_diameter === null || (is_array($rim_diameter) && count($rim_diameter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rim_diameter when calling searchByTireModifications'
            );
        }
        if ($ordering !== null && strlen($ordering) < 1) {
            throw new \InvalidArgumentException('invalid length for "$ordering" when calling SearchByMetricTireApi.searchByTireModifications, must be bigger than or equal to 1.');
        }

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SearchByMetricTireApi.searchByTireModifications, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 0) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SearchByMetricTireApi.searchByTireModifications, must be bigger than or equal to 0.');
        }

        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling SearchByMetricTireApi.searchByTireModifications, must be bigger than or equal to 0.');
        }


        $resourcePath = '/by_tire/search/modifications/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($make !== null) {
            $queryParams['make'] = ObjectSerializer::toQueryValue($make);
        }
        // query params
        if ($model !== null) {
            $queryParams['model'] = ObjectSerializer::toQueryValue($model);
        }
        // query params
        if ($section_width !== null) {
            $queryParams['section_width'] = ObjectSerializer::toQueryValue($section_width);
        }
        // query params
        if ($aspect_ratio !== null) {
            $queryParams['aspect_ratio'] = ObjectSerializer::toQueryValue($aspect_ratio);
        }
        // query params
        if ($rim_diameter !== null) {
            $queryParams['rim_diameter'] = ObjectSerializer::toQueryValue($rim_diameter);
        }
        // query params
        if (is_array($region)) {
            $queryParams['region'] = $region;
        } else
        if ($region !== null) {
            $queryParams['region'] = ObjectSerializer::toQueryValue($region);
        }
        // query params
        if ($mode !== null) {
            $queryParams['mode'] = ObjectSerializer::toQueryValue($mode);
        }
        // query params
        if ($ordering !== null) {
            $queryParams['ordering'] = ObjectSerializer::toQueryValue($ordering);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sectionWidths
     *
     * List section widths (mm)
     *
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \WheelSizeApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \WheelSizeApiClient\Model\SectionWidthMetricReportOutput
     */
    public function sectionWidths($region = null, $ordering = null)
    {
        list($response) = $this->sectionWidthsWithHttpInfo($region, $ordering);
        return $response;
    }

    /**
     * Operation sectionWidthsWithHttpInfo
     *
     * List section widths (mm)
     *
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \WheelSizeApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \WheelSizeApiClient\Model\SectionWidthMetricReportOutput, HTTP status code, HTTP response headers (array of strings)
     */
    public function sectionWidthsWithHttpInfo($region = null, $ordering = null)
    {
        $returnType = '\WheelSizeApiClient\Model\SectionWidthMetricReportOutput';
        $request = $this->sectionWidthsRequest($region, $ordering);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\WheelSizeApiClient\Model\SectionWidthMetricReportOutput',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sectionWidthsAsync
     *
     * List section widths (mm)
     *
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sectionWidthsAsync($region = null, $ordering = null)
    {
        return $this->sectionWidthsAsyncWithHttpInfo($region, $ordering)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sectionWidthsAsyncWithHttpInfo
     *
     * List section widths (mm)
     *
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sectionWidthsAsyncWithHttpInfo($region = null, $ordering = null)
    {
        $returnType = '\WheelSizeApiClient\Model\SectionWidthMetricReportOutput';
        $request = $this->sectionWidthsRequest($region, $ordering);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sectionWidths'
     *
     * @param  string[] $region A **&#x60;Region&#x60;** is the region where the car was officially sold or is still being sold. You can use _**&#x60;GET /regions/&#x60;**_ to get a list of available *&#x60;slug&#x60;* values. (e.g. &#x60;usdm&#x60;) (optional)
     * @param  string $ordering Comma-separated list without spaces. Supported field names: *&#x60;value&#x60;* (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sectionWidthsRequest($region = null, $ordering = null)
    {
        if ($ordering !== null && strlen($ordering) < 1) {
            throw new \InvalidArgumentException('invalid length for "$ordering" when calling SearchByMetricTireApi.sectionWidths, must be bigger than or equal to 1.');
        }


        $resourcePath = '/by_tire/sw/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($region)) {
            $queryParams['region'] = $region;
        } else
        if ($region !== null) {
            $queryParams['region'] = ObjectSerializer::toQueryValue($region);
        }
        // query params
        if ($ordering !== null) {
            $queryParams['ordering'] = ObjectSerializer::toQueryValue($ordering);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('user_key');
        if ($apiKey !== null) {
            $queryParams['user_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
