<?php
/**
 * UpstepsData
 *
 * PHP version 5
 *
 * @category Class
 * @package  WheelSizeApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wheel Fitment API
 *
 * The Wheel Fitment API provides a programmatic gateway to the comprehensive database and services of www.wheel-size.com. This API is expertly designed to retrieve detailed information regarding the vehicle fitment database for rims and tires, encompassing both original equipment (OE) and  aftermarket fitments, along with plus/minus sizing fitment data. Our offerings are further diversified  by including a multitude of country-specific and language-specific options.  We take pride in the extensive coverage of our fitment data, which nearly spans 100% for vehicles manufactured since the year 2000. Moreover, to ensure the utmost accuracy and relevance of the information we provide, our fitment data is meticulously updated on a daily basis.
 *
 * OpenAPI spec version: v2
 * Contact: info@wheel-size.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace WheelSizeApiClient\Model;

use \ArrayAccess;
use \WheelSizeApiClient\ObjectSerializer;

/**
 * UpstepsData Class Doc Comment
 *
 * @category Class
 * @package  WheelSizeApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UpstepsData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UpstepsData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'tire' => '\WheelSizeApiClient\Model\Tire',
        'rim' => '\WheelSizeApiClient\Model\Rim',
        'is_oe' => 'bool',
        'difference' => '\WheelSizeApiClient\Model\Difference'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'tire' => null,
        'rim' => null,
        'is_oe' => null,
        'difference' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tire' => 'tire',
        'rim' => 'rim',
        'is_oe' => 'is_oe',
        'difference' => 'difference'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tire' => 'setTire',
        'rim' => 'setRim',
        'is_oe' => 'setIsOe',
        'difference' => 'setDifference'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tire' => 'getTire',
        'rim' => 'getRim',
        'is_oe' => 'getIsOe',
        'difference' => 'getDifference'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['tire'] = isset($data['tire']) ? $data['tire'] : null;
        $this->container['rim'] = isset($data['rim']) ? $data['rim'] : null;
        $this->container['is_oe'] = isset($data['is_oe']) ? $data['is_oe'] : null;
        $this->container['difference'] = isset($data['difference']) ? $data['difference'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['tire'] === null) {
            $invalidProperties[] = "'tire' can't be null";
        }
        if ($this->container['rim'] === null) {
            $invalidProperties[] = "'rim' can't be null";
        }
        if ($this->container['is_oe'] === null) {
            $invalidProperties[] = "'is_oe' can't be null";
        }
        if ($this->container['difference'] === null) {
            $invalidProperties[] = "'difference' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tire
     *
     * @return \WheelSizeApiClient\Model\Tire
     */
    public function getTire()
    {
        return $this->container['tire'];
    }

    /**
     * Sets tire
     *
     * @param \WheelSizeApiClient\Model\Tire $tire tire
     *
     * @return $this
     */
    public function setTire($tire)
    {
        $this->container['tire'] = $tire;

        return $this;
    }

    /**
     * Gets rim
     *
     * @return \WheelSizeApiClient\Model\Rim
     */
    public function getRim()
    {
        return $this->container['rim'];
    }

    /**
     * Sets rim
     *
     * @param \WheelSizeApiClient\Model\Rim $rim rim
     *
     * @return $this
     */
    public function setRim($rim)
    {
        $this->container['rim'] = $rim;

        return $this;
    }

    /**
     * Gets is_oe
     *
     * @return bool
     */
    public function getIsOe()
    {
        return $this->container['is_oe'];
    }

    /**
     * Sets is_oe
     *
     * @param bool $is_oe False
     *
     * @return $this
     */
    public function setIsOe($is_oe)
    {
        $this->container['is_oe'] = $is_oe;

        return $this;
    }

    /**
     * Gets difference
     *
     * @return \WheelSizeApiClient\Model\Difference
     */
    public function getDifference()
    {
        return $this->container['difference'];
    }

    /**
     * Sets difference
     *
     * @param \WheelSizeApiClient\Model\Difference $difference difference
     *
     * @return $this
     */
    public function setDifference($difference)
    {
        $this->container['difference'] = $difference;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


