<?php
/**
 * Wheel
 *
 * PHP version 5
 *
 * @category Class
 * @package  WheelSizeApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wheel Fitment API
 *
 * The Wheel Fitment API provides a programmatic gateway to the comprehensive database and services of www.wheel-size.com. This API is expertly designed to retrieve detailed information regarding the vehicle fitment database for rims and tires, encompassing both original equipment (OE) and  aftermarket fitments, along with plus/minus sizing fitment data. Our offerings are further diversified  by including a multitude of country-specific and language-specific options.  We take pride in the extensive coverage of our fitment data, which nearly spans 100% for vehicles manufactured since the year 2000. Moreover, to ensure the utmost accuracy and relevance of the information we provide, our fitment data is meticulously updated on a daily basis.
 *
 * OpenAPI spec version: v2
 * Contact: info@wheel-size.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace WheelSizeApiClient\Model;

use \ArrayAccess;
use \WheelSizeApiClient\ObjectSerializer;

/**
 * Wheel Class Doc Comment
 *
 * @category Class
 * @package  WheelSizeApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Wheel implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Wheel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'tire_pressure' => '\WheelSizeApiClient\Model\TirePressure',
        'rim' => 'string',
        'rim_diameter' => 'float',
        'rim_width' => 'float',
        'rim_offset' => 'float',
        'tire' => 'string',
        'tire_sizing_system' => 'string',
        'tire_construction' => 'string',
        'tire_width' => 'float',
        'tire_aspect_ratio' => 'float',
        'tire_diameter' => 'float',
        'tire_section_width' => 'float',
        'tire_is_82series' => 'bool',
        'load_index' => 'int',
        'speed_index' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'tire_pressure' => null,
        'rim' => null,
        'rim_diameter' => null,
        'rim_width' => null,
        'rim_offset' => null,
        'tire' => null,
        'tire_sizing_system' => null,
        'tire_construction' => null,
        'tire_width' => null,
        'tire_aspect_ratio' => null,
        'tire_diameter' => null,
        'tire_section_width' => null,
        'tire_is_82series' => null,
        'load_index' => null,
        'speed_index' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tire_pressure' => 'tire_pressure',
        'rim' => 'rim',
        'rim_diameter' => 'rim_diameter',
        'rim_width' => 'rim_width',
        'rim_offset' => 'rim_offset',
        'tire' => 'tire',
        'tire_sizing_system' => 'tire_sizing_system',
        'tire_construction' => 'tire_construction',
        'tire_width' => 'tire_width',
        'tire_aspect_ratio' => 'tire_aspect_ratio',
        'tire_diameter' => 'tire_diameter',
        'tire_section_width' => 'tire_section_width',
        'tire_is_82series' => 'tire_is_82series',
        'load_index' => 'load_index',
        'speed_index' => 'speed_index'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tire_pressure' => 'setTirePressure',
        'rim' => 'setRim',
        'rim_diameter' => 'setRimDiameter',
        'rim_width' => 'setRimWidth',
        'rim_offset' => 'setRimOffset',
        'tire' => 'setTire',
        'tire_sizing_system' => 'setTireSizingSystem',
        'tire_construction' => 'setTireConstruction',
        'tire_width' => 'setTireWidth',
        'tire_aspect_ratio' => 'setTireAspectRatio',
        'tire_diameter' => 'setTireDiameter',
        'tire_section_width' => 'setTireSectionWidth',
        'tire_is_82series' => 'setTireIs82series',
        'load_index' => 'setLoadIndex',
        'speed_index' => 'setSpeedIndex'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tire_pressure' => 'getTirePressure',
        'rim' => 'getRim',
        'rim_diameter' => 'getRimDiameter',
        'rim_width' => 'getRimWidth',
        'rim_offset' => 'getRimOffset',
        'tire' => 'getTire',
        'tire_sizing_system' => 'getTireSizingSystem',
        'tire_construction' => 'getTireConstruction',
        'tire_width' => 'getTireWidth',
        'tire_aspect_ratio' => 'getTireAspectRatio',
        'tire_diameter' => 'getTireDiameter',
        'tire_section_width' => 'getTireSectionWidth',
        'tire_is_82series' => 'getTireIs82series',
        'load_index' => 'getLoadIndex',
        'speed_index' => 'getSpeedIndex'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['tire_pressure'] = isset($data['tire_pressure']) ? $data['tire_pressure'] : null;
        $this->container['rim'] = isset($data['rim']) ? $data['rim'] : null;
        $this->container['rim_diameter'] = isset($data['rim_diameter']) ? $data['rim_diameter'] : null;
        $this->container['rim_width'] = isset($data['rim_width']) ? $data['rim_width'] : null;
        $this->container['rim_offset'] = isset($data['rim_offset']) ? $data['rim_offset'] : null;
        $this->container['tire'] = isset($data['tire']) ? $data['tire'] : null;
        $this->container['tire_sizing_system'] = isset($data['tire_sizing_system']) ? $data['tire_sizing_system'] : null;
        $this->container['tire_construction'] = isset($data['tire_construction']) ? $data['tire_construction'] : null;
        $this->container['tire_width'] = isset($data['tire_width']) ? $data['tire_width'] : null;
        $this->container['tire_aspect_ratio'] = isset($data['tire_aspect_ratio']) ? $data['tire_aspect_ratio'] : null;
        $this->container['tire_diameter'] = isset($data['tire_diameter']) ? $data['tire_diameter'] : null;
        $this->container['tire_section_width'] = isset($data['tire_section_width']) ? $data['tire_section_width'] : null;
        $this->container['tire_is_82series'] = isset($data['tire_is_82series']) ? $data['tire_is_82series'] : null;
        $this->container['load_index'] = isset($data['load_index']) ? $data['load_index'] : null;
        $this->container['speed_index'] = isset($data['speed_index']) ? $data['speed_index'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['rim'] === null) {
            $invalidProperties[] = "'rim' can't be null";
        }
        if ((mb_strlen($this->container['rim']) < 1)) {
            $invalidProperties[] = "invalid value for 'rim', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['tire'] === null) {
            $invalidProperties[] = "'tire' can't be null";
        }
        if ((mb_strlen($this->container['tire']) < 1)) {
            $invalidProperties[] = "invalid value for 'tire', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['tire_is_82series'] === null) {
            $invalidProperties[] = "'tire_is_82series' can't be null";
        }

        if (null !== $this->container['speed_index'] && (mb_strlen($this->container['speed_index']) < 1)) {
            $invalidProperties[] = "invalid value for 'speed_index', the character length must be bigger than or equal to 1.";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tire_pressure
     *
     * @return null|\WheelSizeApiClient\Model\TirePressure
     */
    public function getTirePressure()
    {
        return $this->container['tire_pressure'];
    }

    /**
     * Sets tire_pressure
     *
     * @param null|\WheelSizeApiClient\Model\TirePressure $tire_pressure Tire pressure in different units (can be null)
     *
     * @return $this
     */
    public function setTirePressure($tire_pressure)
    {
        $this->container['tire_pressure'] = $tire_pressure;

        return $this;
    }

    /**
     * Gets rim
     *
     * @return string
     */
    public function getRim()
    {
        return $this->container['rim'];
    }

    /**
     * Sets rim
     *
     * @param string $rim Formatter rim size (e.g. `7Jx18 ET38`, can be __*`\"\"`*__)
     *
     * @return $this
     */
    public function setRim($rim)
    {

        if ((mb_strlen($rim) < 1)) {
            //throw new \InvalidArgumentException('invalid length for $rim when calling Wheel., must be bigger than or equal to 1.');
        }

        $this->container['rim'] = $rim;

        return $this;
    }

    /**
     * Gets rim_diameter
     *
     * @return float|null
     */
    public function getRimDiameter()
    {
        return $this->container['rim_diameter'];
    }

    /**
     * Sets rim_diameter
     *
     * @param float|null $rim_diameter Rim diameter, in (e.g. 18.0, can be null)
     *
     * @return $this
     */
    public function setRimDiameter($rim_diameter)
    {
        $this->container['rim_diameter'] = $rim_diameter;

        return $this;
    }

    /**
     * Gets rim_width
     *
     * @return float|null
     */
    public function getRimWidth()
    {
        return $this->container['rim_width'];
    }

    /**
     * Sets rim_width
     *
     * @param float|null $rim_width Rim width, in (e.g. 7.0, can be null)
     *
     * @return $this
     */
    public function setRimWidth($rim_width)
    {
        $this->container['rim_width'] = $rim_width;

        return $this;
    }

    /**
     * Gets rim_offset
     *
     * @return float|null
     */
    public function getRimOffset()
    {
        return $this->container['rim_offset'];
    }

    /**
     * Sets rim_offset
     *
     * @param float|null $rim_offset Rim offset, mm (e.g. 38.0, can be null)
     *
     * @return $this
     */
    public function setRimOffset($rim_offset)
    {
        $this->container['rim_offset'] = $rim_offset;

        return $this;
    }

    /**
     * Gets tire
     *
     * @return string
     */
    public function getTire()
    {
        return $this->container['tire'];
    }

    /**
     * Sets tire
     *
     * @param string $tire Formatted tire size (e.g. `225/55R18`, can be __*`\"\"`*__)
     *
     * @return $this
     */
    public function setTire($tire)
    {

        if ((mb_strlen($tire) < 1)) {
            //throw new \InvalidArgumentException('invalid length for $tire when calling Wheel., must be bigger than or equal to 1.');
        }

        $this->container['tire'] = $tire;

        return $this;
    }

    /**
     * Gets tire_sizing_system
     *
     * @return string|null
     */
    public function getTireSizingSystem()
    {
        return $this->container['tire_sizing_system'];
    }

    /**
     * Sets tire_sizing_system
     *
     * @param string|null $tire_sizing_system Tire sizing system (e.g. metric, can be null)
     *
     * @return $this
     */
    public function setTireSizingSystem($tire_sizing_system)
    {
        $this->container['tire_sizing_system'] = $tire_sizing_system;

        return $this;
    }

    /**
     * Gets tire_construction
     *
     * @return string|null
     */
    public function getTireConstruction()
    {
        return $this->container['tire_construction'];
    }

    /**
     * Sets tire_construction
     *
     * @param string|null $tire_construction Tire constriction code (e.g. R, can be null)
     *
     * @return $this
     */
    public function setTireConstruction($tire_construction)
    {
        $this->container['tire_construction'] = $tire_construction;

        return $this;
    }

    /**
     * Gets tire_width
     *
     * @return float|null
     */
    public function getTireWidth()
    {
        return $this->container['tire_width'];
    }

    /**
     * Sets tire_width
     *
     * @param float|null $tire_width Tire width, mm (e.g. 225.0, can be null)
     *
     * @return $this
     */
    public function setTireWidth($tire_width)
    {
        $this->container['tire_width'] = $tire_width;

        return $this;
    }

    /**
     * Gets tire_aspect_ratio
     *
     * @return float|null
     */
    public function getTireAspectRatio()
    {
        return $this->container['tire_aspect_ratio'];
    }

    /**
     * Sets tire_aspect_ratio
     *
     * @param float|null $tire_aspect_ratio Aspect ratio, % (e.g. 55.0, can be null)
     *
     * @return $this
     */
    public function setTireAspectRatio($tire_aspect_ratio)
    {
        $this->container['tire_aspect_ratio'] = $tire_aspect_ratio;

        return $this;
    }

    /**
     * Gets tire_diameter
     *
     * @return float|null
     */
    public function getTireDiameter()
    {
        return $this->container['tire_diameter'];
    }

    /**
     * Sets tire_diameter
     *
     * @param float|null $tire_diameter High flotation tire diameter, in (e.g. 31.0, can be null)
     *
     * @return $this
     */
    public function setTireDiameter($tire_diameter)
    {
        $this->container['tire_diameter'] = $tire_diameter;

        return $this;
    }

    /**
     * Gets tire_section_width
     *
     * @return float|null
     */
    public function getTireSectionWidth()
    {
        return $this->container['tire_section_width'];
    }

    /**
     * Sets tire_section_width
     *
     * @param float|null $tire_section_width High flotation section width, in (e.g. 10.5, can be null)
     *
     * @return $this
     */
    public function setTireSectionWidth($tire_section_width)
    {
        $this->container['tire_section_width'] = $tire_section_width;

        return $this;
    }

    /**
     * Gets tire_is_82series
     *
     * @return bool
     */
    public function getTireIs82series()
    {
        return $this->container['tire_is_82series'];
    }

    /**
     * Sets tire_is_82series
     *
     * @param bool $tire_is_82series Is an old tire with assumed aspect ratio 82%
     *
     * @return $this
     */
    public function setTireIs82series($tire_is_82series)
    {
        $this->container['tire_is_82series'] = $tire_is_82series;

        return $this;
    }

    /**
     * Gets load_index
     *
     * @return int|null
     */
    public function getLoadIndex()
    {
        return $this->container['load_index'];
    }

    /**
     * Sets load_index
     *
     * @param int|null $load_index Load index (e.g. 98, can be null)
     *
     * @return $this
     */
    public function setLoadIndex($load_index)
    {
        $this->container['load_index'] = $load_index;

        return $this;
    }

    /**
     * Gets speed_index
     *
     * @return string|null
     */
    public function getSpeedIndex()
    {
        return $this->container['speed_index'];
    }

    /**
     * Sets speed_index
     *
     * @param string|null $speed_index Speed rating (e.g. H, can be null)
     *
     * @return $this
     */
    public function setSpeedIndex($speed_index)
    {

        if (null !== $speed_index && (mb_strlen($speed_index) < 1)) {
            throw new \InvalidArgumentException('invalid length for $speed_index when calling Wheel., must be bigger than or equal to 1.');
        }

        $this->container['speed_index'] = $speed_index;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


